import { Geist, Geist_Mono, Heebo, Open_Sans, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const heebo = Heebo({
  variable: "--font-heebo-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: "700",
});
const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});
const opensans = Open_Sans ({
  variable: "--font-opensans-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "FLY HIGH CONSULTANTS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} '${opensans.variable} '${poppins.variable} '${roboto.variable} '${heebo.variable}   antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
